name = "hy3n4-news"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true

[ai]
binding = "AI"
remote = true

[[vectorize]]
binding = "VECTORIZE"
index_name = "news-topics-index-dev"
remote = true

[triggers]
crons = ["*/30 * * * *"]

[[queues.producers]]
binding = "NEWS_PROCESSING_QUEUE"
queue = "news-processing-queue-dev"

[[queues.consumers]]
queue = "news-processing-queue-dev"
max_batch_size = 50
max_batch_timeout = 5
max_concurrency = 1

[[d1_databases]]
binding = "DB"
database_name = "news-db"
database_id = "15bbb429-a4bf-4c66-81fb-73ad4ea7e3ff"
remote = true

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"

[ratelimits.simple]
limit = 15
period = 10

[vars]
GOOGLE_CLIENT_ID = "5439287092-mfrbcjgop304q6d8693avajaagc8gk87.apps.googleusercontent.com"
EMBEDDING_MODEL = "@cf/baai/bge-m3"
LLM_MODEL = "@cf/google/gemma-3-12b-it"

[env.production]
routes = [
  { pattern = "hy3n4.news", custom_domain = true },
  { pattern = "www.hy3n4.news", custom_domain = true }
]

[env.production.triggers]
crons = ["*/30 * * * *"]

[env.production.vars]
GOOGLE_CLIENT_ID = "5439287092-mfrbcjgop304q6d8693avajaagc8gk87.apps.googleusercontent.com"
EMBEDDING_MODEL = "@cf/baai/bge-m3"
LLM_MODEL = "@cf/google/gemma-3-12b-it"

[[env.production.d1_databases]]
binding = "DB"
database_name = "news-db"
database_id = "15bbb429-a4bf-4c66-81fb-73ad4ea7e3ff"

[env.production.ai]
binding = "AI"

[[env.production.vectorize]]
binding = "VECTORIZE"
index_name = "news-topics-index"

[[env.production.queues.producers]]
binding = "NEWS_PROCESSING_QUEUE"
queue = "news-processing-queue"

[[env.production.queues.consumers]]
queue = "news-processing-queue"
max_batch_size = 50
max_batch_timeout = 5
max_concurrency = 1

[[env.production.ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1002"

[env.production.ratelimits.simple]
limit = 3
period = 10

